
// =====================================================================================
//
// SupportingBases Engine - Core Contracts
//
// This file is the single source of truth for all data structures (contracts) used
// across the core engine. By maintaining a centralized and well-defined set of
// interfaces, we ensure type safety, clarity, and consistency between different
// layers and services of the application.
//
// =====================================================================================

/**
 * Defines the standard labels for financial scenarios.
 */
export enum CenarioLabel {
  PESSIMISTA = "Pessimista",
  BASE = "Base",
  OTIMISTA = "Otimista",
}

/**
 * Defines the categories for strategic recommendations.
 */
export enum RecommendationCategory {
  AJUSTE_ESTRATEGIA = "Ajuste de Estratégia",
  OTIMIZACAO_CARTEIRA = "Otimização de Carteira",
  MANUTENCAO_PLANO = "Manutenção do Plano",
  GESTAO_RISCO = "Gestão de Risco",
}

/**
 * Defines the severity levels for alerts.
 */
export enum AlertType {
  INFO = "Informativo",
  AVISO = "Aviso",
  ALERTA = "Alerta",
}

/**
 * Represents the core input for a financial simulation.
 * This contract is immutable to ensure predictable calculations.
 */
export interface SimulationInput {
  /** Current total assets or principal amount. */
  readonly patrimonioAtual: number;
  /** Fixed monthly contribution amount. */
  readonly aporteMensal: number;
  /** Expected average annual return rate (as a percentage, e.g., 8 for 8%). */
  readonly taxaRetornoAnual: number;
  /** The time frame for the simulation, in months. */
  readonly horizonteMeses: number;
  /** The user's financial goal to be reached. */
  readonly metaFinanceira: number;
  /** The user's declared risk profile. */
  readonly perfilRisco: string;
}

/**
 * Represents the outcome of a single financial projection.
 */
export interface ProjectionResult {
  /** The total projected value of the assets at the end of the horizon. */
  readonly patrimonioProjetado: number;
  /** The overall profitability as a percentage of the total amount invested. */
  readonly rentabilidadePercentual: number;
}

/**
 * Represents the evaluation of a single financial scenario (e.g., pessimistic, base, optimistic).
 * It extends the basic projection with scenario-specific context.
 */
export interface ScenarioEvaluation extends ProjectionResult {
  /** The label identifying the scenario. */
  readonly label: CenarioLabel;
  /** The annual return rate used for this specific scenario's projection. */
  readonly taxaRetornoAnual: number;
}

/**
 * Represents a strategic recommendation generated by the engine.
 */
export interface StrategicRecommendation {
  /** The category of the recommendation. */
  readonly category: RecommendationCategory;
  /** The concise title of the recommendation. */
  readonly title: string;
  /** A detailed explanation of the recommendation. */
  readonly description: string;
  /** A numerical score (0-1) indicating the plan's feasibility. */
  readonly scoreViabilidade: number;
  /** A numerical score indicating the estimated risk or volatility. */
  readonly riscoEstimado: number;
}

/**
 * Represents a proactive alert about a potential issue or point of interest.
 */
export interface Alert {
  /** The severity level of the alert. */
  readonly type: AlertType;
  /** The title of the alert. */
  readonly title: string;
  /** The detailed alert message. */
  readonly message: string;
}

/**
 * Contains metadata about the generated response.
 */
export interface ContractMetadata {
  /** The version of the contract structure. */
  readonly contractVersion: string;
  /** The ISO 8601 timestamp of when the response was generated. */
  readonly generatedAt: string;
  /** An optional identifier for tracking the request end-to-end. */
  readonly correlationId?: string;
}

/**
 * The main response contract for the SupportingBases Engine.
 * It aggregates all analysis results into a single, comprehensive object.
 */
export interface SupportingBasesResponse {
  /** The original input parameters used for the simulation. */
  readonly input: SimulationInput;
  /** A list of evaluated financial scenarios. */
  readonly cenarios: readonly ScenarioEvaluation[];
  /** A list of strategic recommendations. */
  readonly recomendacoes: readonly StrategicRecommendation[];
  /** A list of proactive alerts. */
  readonly alertas: readonly Alert[];
  /** Metadata about the response. */
  readonly metadata: ContractMetadata;
}
